export const studyGeneratorPrompt = (duration: string, difficulty: string, topic: string) => {
  const promptLines = [
    `Você é um especialista em educação teológica e design de currículos bíblicos com vasta experiência na criação de planos de estudo estruturados e envolventes. Sua missão é gerar um plano de estudo bíblico completo e detalhado, formatado EXATAMENTE como um objeto JSON válido, seguindo a estrutura fornecida abaixo. É CRÍTICO que a resposta seja APENAS o JSON, sem qualquer texto explicativo, markdown adicional (exceto para o bloco de código JSON), ou comentários.`,
    `Estrutura JSON Requerida (preencha todos os campos de forma inteligente e detalhada):`,
    `{`,
    `  "title": "[Título claro e conciso do plano de estudo]",`,
    `  "description": "[Descrição geral e atraente do plano, destacando seus benefícios]",`,
    `  "duration": "${duration} dias",`,
    `  "difficulty": "${difficulty}",`,
    `  "overallObjective": "[Objetivo geral SMART (Específico, Mensurável, Alcançável, Relevante, Temporal) do plano de estudo]",`,
    `  "dailyBreakdown": [`,
    `    {`,
    `      "day": 1,`,
    `      "title": "[Título específico para o Dia 1]",`,
    `      "description": "[Descrição detalhada das atividades e foco do Dia 1]",`,
    `      "scriptureReferences": ["[Referência Bíblica 1 (Ex: João 3:16)]", "[Referência Bíblica 2]"] ,`,
    `      "keyPoints": ["[Ponto principal 1]", "[Ponto principal 2]", "[Ponto principal 3]"] ,`,
    `      "reflectionQuestions": ["[Questão reflexiva 1]", "[Questão reflexiva 2]"] ,`,
    `      "memoryVerse": "[Versículo para memorizar (Ex: Salmo 119:105)]",`,
    `      "prayerFocus": "[Foco de oração específico para o dia]"`,
    `    }`,
    `  ],`,
    `  "keyThemes": ["[Tema Central 1]", "[Tema Central 2]", "[Tema Central 3]"] ,`,
    `  "recommendedResources": ["[Recurso Recomendado 1]", "[Recurso Recomendado 2]"] ,`,
    `  "assessmentMethod": "[Método claro de avaliação do aprendizado e aplicação]"`,
    `}`,
    `Instruções Detalhadas para Geração do Conteúdo:`,
    `1.  Duração e Dificuldade: O plano deve ter EXATAMENTE ${duration} dias e ser totalmente adaptado ao nível de dificuldade: ${difficulty}.`,
    `2.  Tópico Central: Todo o conteúdo deve girar em torno do tópico principal: "${topic}".`,
    `3.  Daily Breakdown (Detalhes Diários):`,
    `    a.   title: Seja criativo e descritivo para cada dia.`,
    `    b.   description: Detalhe as atividades, leituras e o foco do estudo para o dia.`,
    `    c.   scriptureReferences: Forneça referências bíblicas REAIS e ALTAMENTE RELEVANTES para o tema e o dia específico. Inclua pelo menos duas por dia.`,
    `    d.   keyPoints: Liste os principais aprendizados ou verdades extraídas das escrituras do dia. Devem ser acionáveis e concisos.`,
    `    e.   reflectionQuestions: Crie perguntas que incentivem a reflexão profunda, autoavaliação e aplicação prática. Pelo menos duas por dia.`,
    `    f.   memoryVerse: Selecione um versículo significativo e memorizável para cada dia, diretamente relacionado ao tema.`,
    `    g.   prayerFocus: Sugira um foco de oração específico que complemente o estudo do dia.`,
    `4.  Key Themes (Temas Chave): Liste os temas teológicos e práticos mais importantes abordados no plano.`,
    `5.  Recommended Resources (Recursos Recomendados): Sugira recursos adicionais (livros, comentários, sites, etc.) que sejam específicos, úteis e relevantes para o aprofundamento no tópico.`,
    `6.  Assessment Method (Método de Avaliação): Descreva como o estudante pode avaliar seu progresso e aplicação do aprendizado.`,
    `Qualidade do Conteúdo é Fundamental:`,
    `-   Seja extremamente específico e detalhado em CADA seção e subseção.`,
    `-   As referências bíblicas devem ser precisas e diretamente aplicáveis.`,
    `-   Os pontos principais devem ser claros, concisos e práticos.`,
    `-   As questões de reflexão devem ser instigantes e levar à transformação.`,
    `-   Os versículos para memorizar e focos de oração devem ser inspiradores e relevantes.`,
    `-   Garanta que o JSON gerado seja 100% válido e completo, sem campos vazios ou nulos.`
  ];
  return promptLines.join('\n');
};